name: foliate
title: Foliate
version: git
grade: stable
adopt-info: foliate
license: GPL-3.0+

base: core18
confinement: strict

apps:
  foliate:
    command: usr/bin/com.github.johnfactotum.Foliate
    extensions: [gnome-3-28]
    plugs:
      - gsettings # For desktop theme detection under Wayland session
      - home
    slots:
      - dbus-daemon
    common-id: com.github.johnfactotum.Foliate
    desktop: usr/share/applications/com.github.johnfactotum.Foliate.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/gnome-platform/usr/lib/
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/gjs/girepository-1.0

layout:
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs

parts:
  foliate:
    plugin: meson
    source: https://github.com/johnfactotum/foliate.git
    source-branch: 1.x
    meson-parameters: [--prefix=/snap/foliate/current/usr]
    build-packages:
      - libgjs-dev
      - gettext
    override-pull: |
      snapcraftctl pull
      # Point icon to the correct location
      sed -i.bak -e 's|Icon=com.github.johnfactotum.Foliate|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.johnfactotum.Foliate.svg|g' data/com.github.johnfactotum.Foliate.desktop.in
    organize:
      snap/foliate/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.johnfactotum.Foliate.appdata.xml]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate
