name: foliate
title: Foliate
version: 'git'
grade: stable
summary: Foliate is a simple and modern GTK eBook viewer.
description: |
  Foliate is a simple and modern GTK eBook viewer.

  Features include:

  * Two-page view and scrolled view
  * Customize font and line-spacing
  * Light, sepia, dark, and invert mode
  * Reading progress slider with chapter marks
  * Bookmarks and annotations
  * Find in book
  * Quick dictionary lookup

base: core18
confinement: strict

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate

apps:
  foliate:
    command: usr/bin/com.github.johnfactotum.Foliate
    extensions: [gnome-3-28]
    plugs:
      - gsettings # For desktop theme detection under Wayland session
      - home
    slots:
      - dbus-daemon
    common-id: com.github.johnfactotum.Foliate.desktop
    desktop: usr/share/applications/com.github.johnfactotum.Foliate.desktop

parts:
  foliate:
    plugin: meson
    meson-parameters: [--prefix=/snap/foliate/current/usr]
    organize:
      snap/foliate/current/usr: usr
    source: https://github.com/johnfactotum/foliate.git
    build-packages:
      - libgjs-dev
    override-pull: |
      snapcraftctl pull
      # Point icon to the correct location
      sed -i.bak -e 's|Icon=com.github.johnfactotum.Foliate|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.johnfactotum.Foliate.svg|g' data/com.github.johnfactotum.Foliate.desktop.in
