name: foliate
title: Foliate
version: '0.1'
grade: stable
summary: Foliate is a simple and modern GTK eBook viewer.
description: |
  Foliate is a simple and modern GTK eBook viewer.

  Features include:

  * Two-page view and scrolled view
  * Customize font and line-spacing
  * Light, sepia, dark, and invert mode
  * Reading progress slider with chapter marks
  * Bookmarks and annotations
  * Find in book
  * Quick dictionary lookup

base: core18
confinement: strict

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

apps:
  foliate:
    command: usr/bin/com.github.johnfactotum.Foliate
    command-chain:
      - bin/desktop-launch
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - gsettings # For desktop theme detection under Wayland session
      - home
    slots:
      - dbus-daemon
    common-id: com.github.johnfactotum.Foliate.desktop
    desktop: usr/share/applications/com.github.johnfactotum.Foliate.desktop
    environment:
      DISABLE_WAYLAND: "1"

parts:
  foliate:
    plugin: meson
    meson-parameters: [--prefix=/snap/foliate/current/usr]
    organize:
      snap/foliate/current/usr: usr
    source: https://github.com/johnfactotum/foliate.git
    build-packages:
      - desktop-file-utils
      - gettext
      - appstream-util
      - libglib2.0-dev
      - libgjs-dev
    override-pull: |
      snapcraftctl pull
      # Point to the snapped version of gjs
      sed -i.bak -e 's|@GJS@|/snap/foliate/current/usr/bin/gjs|g' src/com.github.johnfactotum.Foliate.in

      # Point icon to the correct location
      sed -i.bak -e 's|Icon=com.github.johnfactotum.Foliate|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.johnfactotum.Foliate.svg|g' data/com.github.johnfactotum.Foliate.desktop.in

    after: [desktop-gnome-platform]

  libraries:
    plugin: nil
    stage-packages:
      - gjs      
      - gir1.2-webkit2-4.0
    # prime:
    #   - "usr/bin/gjs*"

  # This part installs the `desktop-launch` script which initialises desktop
  # features such as fonts, themes and the XDG environment.
  # 
  # It is copied straight from the snapcraft desktop helpers project. Please
  # periodically check the source for updates and copy the changes.
  #    https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  # 
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - gcc
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
